<?php

return [
    // Keep local overrides in config/local.php (gitignored) or use WORKER_* environment variables.
    'api_base_url' => getenv('WORKER_API_BASE_URL') ?: '',
    'environment' => getenv('WORKER_ENV') ?: 'development',
    'allow_insecure_local_api' => filter_var(getenv('WORKER_ALLOW_INSECURE_LOCAL_API') ?: 'false', FILTER_VALIDATE_BOOL),
    'credential_store' => getenv('WORKER_CREDENTIAL_STORE') ?: (PHP_OS_FAMILY === 'Windows' ? 'windows' : 'file-dev'),
    'credential_reference' => getenv('WORKER_CREDENTIAL_REFERENCE') ?: 'ScholarshipTracker.CrawlerWorker',
    'worker_uuid' => getenv('WORKER_UUID') ?: '',
    'protocol_version' => 1,
    'software_version' => '0.1.0',
    'connect_timeout_seconds' => 5,
    'request_timeout_seconds' => 20,
    'heartbeat_interval_seconds' => 30,
    'poll_interval_seconds' => 5,
    'max_api_retries' => 3,
    'retry_base_delay_ms' => 250,
    'retry_max_delay_ms' => 5000,
    'max_api_response_bytes' => 1048576,
    'max_spool_entry_bytes' => 10485760,
    'spool_directory' => dirname(__DIR__).'/storage/spool',
    'log_directory' => dirname(__DIR__).'/storage/logs',
    'identity_file' => dirname(__DIR__).'/storage/worker-state.json',
    'development_credential_file' => dirname(__DIR__).'/storage/credentials.dev.json',
    'fetch_connect_timeout_seconds' => 5,
    'fetch_timeout_seconds' => 30,
    'fetch_operation_timeout_seconds' => 90,
    'max_fetch_bytes' => 4194304,
    'max_redirects' => 4,
    'minimum_source_delay_ms' => 1000,
    'allow_http_sources' => false,
    'allowed_content_types' => ['text/html', 'application/xhtml+xml', 'application/json', 'application/pdf'],
];
